# Generated by Django 5.2.8 on 2025-11-09 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures')),
                ('song_location', models.FileField(upload_to='song_locations')),
                ('artist', models.ManyToManyField(to='api.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_method', models.CharField(choices=[('CUSTOM ORDER', 'custom order'), ('TITLE', 'title'), ('ARTIST', 'artist'), ('ALBUM', 'album'), ('RECENTLY ADDED', 'recently added')])),
                ('shuffle', models.BooleanField(default=False)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.song')),
            ],
        ),
    ]
