# Generated by Django 5.2.8 on 2025-11-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='playlist',
            name='song_id',
            field=models.ManyToManyField(to='api.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.artist'),
            preserve_default=False,
        ),
    ]
