# Generated by Django 5.2.8 on 2025-11-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_playlist_playlist_name_remove_playlist_song_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='song_id',
            field=models.ManyToManyField(related_name='playlists', to='api.song'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='sort_method',
            field=models.CharField(choices=[('CUSTOM ORDER', 'custom order'), ('TITLE', 'title'), ('ARTIST', 'artist'), ('ALBUM', 'album'), ('RECENTLY ADDED', 'recently added')], default='CUSTOM ORDER', max_length=50),
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AlterField(
            model_name='song',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(related_name='songs', to='api.artist'),
        ),
    ]
