# Generated by Django 5.2.8 on 2025-11-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_song_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
