# Generated by Django 5.2.8 on 2025-11-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_song_artist_remove_song_movie_delete_artist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
